CREATE DATABASE IF NOT EXISTS `tcc` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `tcc`;

DROP TABLE IF EXISTS `login`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `login` (
  `id_user` int(11) NOT NULL AUTO_INCREMENT,
  `nome` varchar(30) DEFAULT NULL,
  `senha` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id_user`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT COLLATE=utf8_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `login` (`id_user`, `nome`, `senha`) VALUES
(1, 'admin', '202cb962ac59075b964b07152d234b70');




CREATE TABLE POLO (
ID_POLO INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(60) UNIQUE NOT NULL
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE CURSO (
ID_CURSO INT AUTO_INCREMENT,
COD VARCHAR(3) UNIQUE,
NOME VARCHAR(80) NOT NULL,
POLO INT NOT NULL, 
PRIMARY KEY (ID_CURSO, COD),
FOREIGN KEY (POLO) REFERENCES POLO(ID_POLO)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE ALUNO (
MATRICULA VARCHAR(10) PRIMARY KEY UNIQUE NOT NULL,
NOME VARCHAR(150) NOT NULL, 
ANO_INGRESSO smallint NOT NULL,
SEMESTRE_INGRESSO TINYINT NOT NULL,
DOCUMENTOS LONGBLOB,
CURSO_ALUNO INT NOT NULL,
FOREIGN KEY (CURSO_ALUNO) REFERENCES CURSO(ID_CURSO)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


-- INSERT NA TABELA POLO


INSERT INTO POLO (NOME) VALUES ('Angra dos Reis');
INSERT INTO POLO (NOME) VALUES ('Campos dos Goytacazes');
INSERT INTO POLO (NOME) VALUES ('Curso à Distância (CEDERJ)');
INSERT INTO POLO (NOME) VALUES ('Macaé');
INSERT INTO POLO (NOME) VALUES ('Niterói');
INSERT INTO POLO (NOME) VALUES ('Nova Friburgo');
INSERT INTO POLO (NOME) VALUES ('Rio das Ostras');
INSERT INTO POLO (NOME) VALUES ('Santo Antônio de Pádua');
INSERT INTO POLO (NOME) VALUES ('Volta Redonda');


-- INSERT NO CURSO

INSERT INTO CURSO (COD, NOME, POLO) VALUES ('001', 'BIBLIOTECONOMIA E DOCUMENTAÇÃO', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('002', 'HISTÓRIA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('003', 'GEOGRAFIA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('004', 'CIÊNCIAS ECONÔMICAS', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('005', 'CIÊNCIAS SOCIAIS', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('006', 'SERVIÇO SOCIAL', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('007', 'DIREITO', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('008', 'ENFERMAGEM E OBSTETRÍCIA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('009', 'NUTRIÇÃO', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('010', 'PEDAGOGIA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('011', 'JORNALISMO', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('012', 'PUBLICIDADE E PROPAGANDA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('013', 'CINEMA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('014', 'ARQUIVOLOGIA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('015', 'FARMÁCIA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('016', 'MEDICINA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('017', 'ODONTOLOGIA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('018', 'MEDICINA VETERINÁRIA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('019', 'ENGENHARIA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('020', 'MATEMÁTICA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('021', 'LETRAS', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('022', 'CIÊNCIAS CONTÁBEIS', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('023', 'ADMINISTRAÇÃO', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('024', 'PSICOLOGIA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('025', 'FÍSICA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('026', 'ARQUITETURA E URBANISMO', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('027', 'ENGENHARIA QUÍMICA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('028', 'QUÍMICA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('029', 'QUÍMICA INDUSTRIAL', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('030', 'COMUNICAÇÃO SOCIAL JORNALISMO / PUBLICIDADE E PROPAGANDA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('031', 'CIÊNCIA DA COMPUTAÇÃO', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('032', 'PEDAGOGIA', 1);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('033', 'PRODUÇÃO CULTURAL', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('034', 'ENFERMAGEM', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('035', 'MATEMÁTICA', 8);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('036', 'SERVIÇO SOCIAL', 2);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('037', 'ENGENHARIA CIVIL', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('038', 'ENGENHARIA ELÉTRICA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('039', 'ENGENHARIA METALÚRGICA', 9);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('040', 'ENGENHARIA MECÂNICA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('041', 'ENGENHARIA DE TELECOMUNICAÇÕES', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('042', 'ENGENHARIA DE PRODUÇÃO', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('043', 'ENGENHARIA AGRÍCOLA E AMBIENTAL', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('044', 'CIÊNCIAS BIOLÓGICAS', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('045', 'ENGENHARIA DE PRODUÇÃO', 9);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('046', 'ENGENHARIA MECÂNICA', 9);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('047', 'TURISMO', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('048', 'BIOMEDICINA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('049', 'ESTUDOS DE MÍDIA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('050', 'GEOFÍSICA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('051', 'ENGENHARIA DE PETRÓLEO', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('052', 'ENGENHARIA DE AGRONEGÓCIOS', 9);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('053', 'ADMINISTRAÇÃO', 9);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('054', 'ESTATÍSTICA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('055', 'EDUCAÇÃO FÍSICA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('056', 'ENGENHARIA DE RECURSOS HÍDRICOS E DO MEIO AMBIENTE', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('057', 'CINEMA E AUDIOVISUAL', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('058', 'FILOSOFIA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('059', 'RELAÇÕES INTERNACIONAIS', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('060', 'CIÊNCIA DA COMPUTAÇÃO', 7);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('061', 'ODONTOLOGIA', 6);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('062', 'PRODUÇÃO CULTURAL', 7);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('063', 'ENGENHARIA DE PRODUÇÃO', 7);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('064', 'SERVIÇO SOCIAL', 7);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('065', 'PEDAGOGIA', 8);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('066', 'CIÊNCIAS ECONÔMICAS', 2);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('067', 'GEOGRAFIA', 2);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('068', 'CIÊNCIAS SOCIAIS', 2);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('069', 'PSICOLOGIA', 7);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('070', 'MATEMÁTICA', 3);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('071', 'TECNOLOGIA COMPUTAÇÃO', 3);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('072', 'EMPREENDEDORISMO E INOVAÇÃO', 3);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('073', 'ENFERMAGEM', 7);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('074', 'ADMINISTRAÇÃO PÚBLICA', 9);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('075', 'CIÊNCIAS CONTÁBEIS', 9);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('076', 'FÍSICA', 9);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('077', 'MATEMÁTICA', 9);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('078', 'QUÍMICA', 9);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('079', 'BIOMEDICINA', 6);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('080', 'FONOAUDIOLOGIA', 6);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('081', 'PSICOLOGIA', 2);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('082', 'FÍSICA', 8);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('083', 'SISTEMAS DE INFORMAÇÃO', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('084', 'DIREITO', 4);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('085', 'CIÊNCIAS ATUARIAIS', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('086', 'ADMINISTRAÇÃO PÚBLICA', 3);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('087', 'LETRAS', 3);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('088', 'DIREITO', 2);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('089', 'HISTÓRIA', 2);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('090', 'DIREITO', 9);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('091', 'PSICOLOGIA', 9);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('092', 'COMPUTAÇÃO', 8);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('093', 'CIÊNCIAS NATURAIS', 8);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('094', 'HOTELARIA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('095', 'CIÊNCIA AMBIENTAL', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('096', 'DESENHO INDUSTRIAL', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('097', 'DISCIPLINA ISOLADA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('098', 'SOCIOLOGIA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('099', 'ANTROPOLOGIA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('100', 'ARTES', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('101', 'GEOGRAFIA', 1);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('102', 'SEGURANÇA PÚBLICA', 5);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('103', 'POLÍTICAS PÚBLICAS', 1);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('104', 'ADMINISTRAÇÃO', 4);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('105', 'CIÊNCIAS CONTÁBEIS', 4);
INSERT INTO CURSO (COD, NOME, POLO) VALUES ('107', 'PROCESSOS GERENCIAIS', 5);



-- CRIAÇÃO DE VIEW CURSO_POLO

CREATE VIEW CURSO_POLO AS
SELECT C.COD, C.NOME AS NOME_CURSO, P.NOME AS NOME_POLO 
FROM CURSO C, POLO P 
WHERE P.ID_POLO = C.POLO
ORDER BY COD;

-- select aluno com nome do polo

select a.matricula, a.nome, a.ano_ingresso, a.semestre_ingresso,
c.nome from aluno a, curso c where a.curso_aluno=c.id_curso;

-- consulta aluno

create view consulta_aluno as
select a.matricula, a.nome, c.nome as curso, p.nome as polo, a.ano_ingresso, a.semestre_ingresso,
a.documentos from aluno a, curso c, polo p where a.curso_aluno=c.id_curso and c.polo=p.id_polo;